repos:
  - repo: https://github.com/akaihola/darker
    rev: v2.1.1
    hooks:
      - id: darker

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.8
    hooks:
      # Run the linter.
      - id: ruff-check
        # FIXME: 这里似乎不会读取项目的ruff.toml文件
        args: []
      # 暂不启用ruff的格式化功能
      # - id: ruff-format

  - repo: https://github.com/pycqa/isort
    rev: 7.0.0 # 使用最新稳定版本
    hooks:
      - id: isort
        args: ["--profile", "black"] # 与 Black 格式化工具兼容的配置

  - repo: https://github.com/opensource-nepal/commitlint
    rev: v1.3.1
    hooks:
      - id: commitlint
